Repository wieslawsoltes/Svg.Skia, pull requests merged in 2022-08, with the labels that each got.

#116 Fix opacity under filter
  src/Svg.Model/Drawables/DrawableBase.cs
  src/Svg.Model/Drawables/DrawableContainer.cs
Labels: size/S

#115 Various fixes related to text
  .gitignore
  build/ImageSharp.props
  samples/AvaloniaSKPictureImageSample/Assets/pservers-pattern-01-b.svg
  samples/AvaloniaSKPictureImageSample/AvaloniaSKPictureImageSample.csproj
  samples/AvaloniaSKPictureImageSample/MainWindow.axaml
  samples/svgc/ImageSharpAssetLoader.cs
  samples/svgc/Item.cs
  samples/svgc/Program.cs
  samples/svgc/Settings.cs
  src/Avalonia.Svg/AvaloniaAssetLoader.cs
  src/Avalonia.Svg/AvaloniaModelExtensions.cs
  src/ShimSkiaSharp/SKPaint.cs
  src/ShimSkiaSharp/SKTypeface.cs
  src/Svg.Model/Drawables/Elements/TextDrawable.cs
  src/Svg.Model/IAssetLoader.cs
  src/Svg.Model/SvgExtensions.Transforms.cs
  src/Svg.Skia/SkiaAssetLoader.cs
  src/Svg.SourceGenerator.Skia/SkiaGeneratorAssetLoader.cs
  src/Svg.SourceGenerator.Skia/SvgSourceGenerator.cs
  tests/Svg.Skia.UnitTests/SKSvgTests.cs
  tests/Svg.Skia.UnitTests/Svg.Skia.UnitTests.csproj
  tests/Svg.Skia.UnitTests/WindowsTheory.cs
  tests/Tests/Sign in.png
  tests/Tests/Sign in.svg
  tests/Tests/__AJ_Digital_Camera.png
  tests/Tests/__AJ_Digital_Camera.svg
  tests/Tests/__Telefunken_FuBK_test_pattern.png
  tests/Tests/__Telefunken_FuBK_test_pattern.svg
  tests/Tests/__tiger.png
  tests/Tests/__tiger.svg
Labels: size/XXL

#122 Refactor SkiaModelExtensions
  samples/Svg.SourceGenerator.Skia.Sample/Program.cs
  samples/SvgToPng/SKElement.cs
  samples/SvgToPng/ViewModels/MainWindowViewModel.cs
  samples/TestApp.Base/ViewModels/MainWindowViewModel.cs
  src/Svg.Skia/SKPictureExtensions.cs
  src/Svg.Skia/SKSvg.cs
  src/Svg.Skia/SKSvgSettings.cs
  src/Svg.Skia/SkiaAssetLoader.cs
  src/Svg.Skia/SkiaModel.cs
  tests/Svg.Skia.UnitTests/Common/SvgUnitTest.cs
  tests/Svg.Skia.UnitTests/SKSvgSettingsTests.cs
  tests/Svg.Skia.UnitTests/resvgTests.cs
Labels: size/XL
